# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Installing Yarn
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: Build yarn App
    - run: yarn build
    - name: install Surge
    - run: npm install -g surge
    - name: Run Surge
    - run: surge ./build bootcamp_react_hussnain.surge.sh --token ${{ secrets.SURGE_TOKEN }}
